baseURL = "http://sigmonsays.github.io/"
languageCode = "en-us"
title = "sigmonsays"


[menu]

[[menu.main]]
  identifier = 'home'
  name = 'home '
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = 5

[[menu.main]]
  identifier = 'projects'
  name = 'projects '
  pre = "<i class='fa fa-heart'></i>"
  url = '/projects/'
  weight = 20

[[menu.main]]
  identifier = 'misc'
  name = 'misc '
  pre = "<i class='fa fa-heart'></i>"
  url = '/tags/misc/'
  weight = 30

[[menu.main]]
  identifier = 'archives'
  name = 'archives '
  pre = "<i class='fa fa-heart'></i>"
  url = '/archives/'
  weight = 40

[[menu.main]]
  identifier = 'about'
  name = 'about '
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 50
