baseURL = "http://sigmonsays.github.io/"
languageCode = "en-us"
title = "sigmonsays"

[menu]

[[menu.main]]
  identifier = 'archives'
  name = 'archives '
  pre = "<i class='fa fa-heart'></i>"
  url = '/archives/'
  weight = -110

[[menu.main]]
  identifier = 'projects'
  name = 'projects '
  pre = "<i class='fa fa-heart'></i>"
  url = '/tags/projects/'
  weight = -110

[[menu.main]]
  identifier = 'misc'
  name = 'misc '
  pre = "<i class='fa fa-heart'></i>"
  url = '/tags/misc/'
  weight = -110

[[menu.main]]
  identifier = 'about'
  name = 'about '
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110

[[menu.main]]
  identifier = 'index'
  name = 'index '
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = -110
