baseURL = 'https://sigmonsays.github.io/'
languageCode = 'en-us'
title = 'sigmonsays'

[menu]

[[menu.main]]
  identifier = 'home'
  name = 'home '
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = 5

[[menu.main]]
  identifier = 'projects'
  name = 'projects '
  pre = "<i class='fa fa-heart'></i>"
  url = '/projects/'
  weight = 20

[[menu.main]]
  identifier = 'misc'
  name = 'misc '
  pre = "<i class='fa fa-heart'></i>"
  url = '/tags/misc/'
  weight = 30

[[menu.main]]
  identifier = 'archives'
  name = 'archives '
  pre = "<i class='fa fa-heart'></i>"
  url = '/archives/'
  weight = 40

[[menu.main]]
  identifier = 'about'
  name = 'about '
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 50

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^rst2html$' ]
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
