#!/usr/bin/env python
import sys
import os
import subprocess
from datetime import datetime

def zs_vars(filename, var_name):
    result = subprocess.run(['zs', 'vars', filename, var_name], capture_output=True, text=True)
    lines = result.stdout.split("\n")
    line = lines[0]
    return line

path = sys.argv[1]

pages = []

for dirpath, dirnames, filenames in os.walk(path):
    for filename in filenames:
        if not filename.endswith('.md'): continue
        abspath = os.path.join(dirpath, filename)
        relpath = os.path.relpath(abspath, path)
        st = os.stat(abspath)
        mtime = st.st_mtime
        dirname = os.path.dirname(relpath)
        filename = relpath.replace('.md', '.html')
        title = zs_vars(abspath, 'title')

        page = {
            'abspath': abspath,
            'relpath': relpath,
            'dirname': dirname,
            'title': title,
            'mtime': mtime,
            'filename': filename,
        }
        pages.append(page)

# Sort pages by mtime desc
sorted_pages = sorted(pages, key=lambda item: item['mtime'])
for page in pages:
    timestamp = datetime.fromtimestamp(page['mtime']).strftime('%Y/%m/%d')
    print(f"- {page['dirname']} [{page['title']}]({page['filename']}) - {timestamp}")
