---
title: sigmonsays
description: a few things to remember
keywords: go, nix, linux

extensions:
  - anchor
  - d2
  - definitionlist
  - embed
  - fences
  - linkify
  - footnote
  - strikethrough
  - table
  - tasklist
  - typography
  - wikilink
