---
title: zs starter template
description: A starter template for the Zen Static (zs) site generator
keywords: zen, static, zs, starter, template, site, website, template, generator, ssg

extensions:
  - anchor
  - d2
  - definitionlist
  - embed
  - fences
  - linkify
  - footnote
  - strikethrough
  - table
  - tasklist
  - typography
  - wikilink
