#!/bin/sh

GITEA_BASE_URL="https://git.mills.io"
REPO="prologic/zs-starter-template"
BRANCH="main"

url="${GITEA_BASE_URL}/${REPO}/_edit/${BRANCH}/${ZS_FILE}"

printf "<a href=\"%s\" rel=\"nofollow\" target=\"_blank\">✍️ Edit Page on Gitea</a>" "$url"
