#!/usr/bin/env python
import sys
import os
import subprocess
from datetime import datetime

def boolval(x):
    x = str(x).lower()
    return x in [ 'true', 't', 'y', 'yes' ]

def zs_vars(filename, var_name, corce=None):
    result = subprocess.run(['zs', 'vars', filename, var_name], capture_output=True, text=True)
    lines = result.stdout.split("\n")
    line = lines[0]
    if corce == None:
        return line
    return corce(line)

def page_snippet(page, max_lines = 10):
    _contents = open(page['abspath']).readlines()
    contents = []
    start = False
    for line in _contents:
        line = line.strip()
        if line == "---":
            start = not start
        if not start:
            contents.append(line)

    if len(contents) > max_lines:
        contents = contents[:max_lines]
    print("\n".join(contents))

path = sys.argv[1]

pages = []

for dirpath, dirnames, filenames in os.walk(path):
    for filename in filenames:
        if not filename.endswith('.md'): continue
        abspath = os.path.join(dirpath, filename)
        relpath = os.path.relpath(abspath, path)
        st = os.stat(abspath)
        dirname = os.path.dirname(relpath)
        basename = os.path.basename(relpath)
        filename = relpath.replace('.md', '.html')
        date = zs_vars(abspath, 'date')
        title = zs_vars(abspath, 'title')
        draft = zs_vars(abspath, 'draft', boolval)

        page = {
            'abspath': abspath,
            'relpath': relpath,
            'dirname': dirname,
            'basename': basename,
            'title': title,
            'date': date,
            'filename': filename,
            'draft': draft,
        }
        pages.append(page)

# Sort pages by date desc
sorted_pages = sorted(pages, key=lambda item: item['date'], reverse=True)
max_posts = 10
posted = 0
for page in sorted_pages:
    if page['basename'] == 'index.md':
        continue
    if page['draft'] == True:
        continue
    if page['dirname'] == 'tags':
        continue
    if page['date'] == 'none': page['date'] = ''

    posted = posted + 1
    if posted > max_posts:
        break

    print(f"## [{page['title']}]({page['filename']})\n")

    page_snippet(page)
    if page['date']:
        print(f"on **{page['date']}**\n")

# EOF
