#!/bin/sh

set -e

# if [ ! $# = 2 ]; then
#     printf >&2 "Usage: %s <path> prefix [ext]\n" "$(basename "$0")"
#     exit 0
# fi

p="$1"
prefix="$2"
t="${3:-md}"

if [ ! -d "$p" ]; then
    printf >&2 "error: path %s not found\n" "$p"
    exit 1
fi

ls -1 $p/*.$t | while read -r file; do
    name="${name%.*}"

    title="$(zs vars "$file" title)"
    if [ -z "$title" ]; then
        title="$file"
    fi

    echo "- [$title](${prefix}/${name}.html)"
done
