#!/bin/sh

set -e

JS="highlight umbrella"

# Load live.js for non-production builds for faster development
if [ -z "$ZS_PRODUCTION" ]; then
  JS="$JS live"
fi

for js in $JS; do
  printf "<script type=\"application/javascript\" src=\"/assets/js/%s.js\"></script>\n" "$js"
done
