#!/usr/bin/env bash

tags="$( zs var "$ZS_FILE" tags | tr , " ")"

[ -z "$tags" ] && exit 0

echo "<span>"
echo "Tags: "
for tag in $tags
do
  echo "<a href='/tags/${tag}.html'>$tag</a>"
done
echo "</span>"
echo "<hr>"
