name: Publish Site

concurrency:
  group: publish-sigmonsays-github-io
  cancel-in-progress: false  # waits for running job; true would cancel it

on:
   # schedule:
   #   - cron: "0 6 * * *"

   workflow_dispatch:  # allows manual runs

   #push: {}
   push:
     branches:
       - master


jobs:
  publish-site:
    runs-on: host-svc1
    steps:
      - uses: actions/checkout@v3
      - name: build and publish site
        shell: |
          cd "${{ inputs.working_directory }}"
          ./.gitea/workflows/publish-site.sh
