---
title: "sig"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"

indexes:
  tag: "tags"
  category: "categories"
  series: "series"

baseurl: "https://sigmonsays.github.io/"
permalinks:
  post: /:year/:month/:slug/

menu:
  main:
   - Name: "Archive"
     Identifier: "archive"
     URL: "/archive/"
   - Name: "About"
     Identifier: "about"
     URL: "/about/"
   - Name: "Contact"
     Identifier: "contact"
     URL: "/contact/"
   - Name: "Projects"
     Identifier: "projects"
     URL: "/projects/"
   - Name: "Github"
     Identifier: "github"
     URL: "https://github.com/sigmonsays"
   - Name: "PGP"
     Identifier: "PGP"
     URL: "/keybase/"
   - Name: "Interesting Software"
     Identifier: "interesting-software"
     URL: "/notes/interesting-tech/"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
  status: "status"

params:
  Description: "tech, life and random"
  description: "tech, life and random"
  AuthorName: "Sig L"
  GitHubUser: "sigmonsays"
  SidebarRecentLimit: 5

disqusShortname: sigmonsays

