---
title: "sig"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://sigmonsays.github.io/"
permalinks:
  post: /:year/:month/:slug/

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

params:
  Description: "tech, life and random"
  description: "tech, life and random"
  AuthorName: "Sig L"
  GitHubUser: "sigmonsays"
  SidebarRecentLimit: 5

disqusShortname: sigmonsays

